#!/usr/bin/env perl

# Usage:       pclMon [-r|a] [-n 30] 272007
# ------
#              run PixelPcl jobs
#
#       -r     do NOT replicate data to PSI, use local mirror
#       -a     do NOT replicate data to PSI, use AAA
#       -n 30  create py files with 30 input filenames
#
# History:     2016/05/10 First shot
# --------     2016/05/11 Change to one py file per run
#              2016/05/12 Add $opt_n
#              2016/05/13 Add $opt_h: combine and analysis
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('adhn:qr');

my $HOME          = $ENV{'HOME'};
my $BASE          = "$HOME/pixel/pcl/CMSSW_8_0_7/src/DPGAnalysis-SiPixelTools/PCL/test";
my $dasFile       = "$HOME/dasExpress.txt";
my $processedRuns = "$HOME/pclMon.runs";
my $SEPREFIX      = "srm://t3se01.psi.ch:8443/srm/managerv2?SFN=/pnfs/psi.ch/cms/trivcat";
my $submit        = "$HOME/perl/run";

if (!$opt_n) {
    $opt_n = -1;
}

# ---------------------------------------
# -- query: check for new runs to process
# ---------------------------------------
if ($opt_q) {
    @runs = checkForNewRuns();
    # -- submit them!
    chdir($BASE);
    foreach $r (@runs) {
	print "pclMon -a -n 20 $r\n";
	if (!$opt_d) {
	    system("./pclMon -a -n 20 $r > cronlog/pclMon-$r.log");
	    open(APP, ">>$processedRuns") || die "cannot open $processedRuns $!";
	    print APP "$r\n";
	    close(APP);
	}
    }
    exit(0);
}

# --------------------------------
# -- run harvest step
# --------------------------------
if ($opt_h) {
    chdir("$BASE");
    my @runs = ();
    # -- read in all processed runs
    opendir(D, ".") || die "Can't open directory: $!\n";
    while (my $f = readdir(D)) {
	if ($f =~ /run-[0-9]{6}$/) {
	    $f =~ s/run-//;
	    push(@runs, $f);
	}
    }
    closedir(D);

    # -- sort them
    sub numerically {$a <=> $b;}
    @runs = sort numerically @runs;

    # -- now check which ones have not been combined
    my $oldRun = -1;
    chdir("..");
    opendir(D, ".") || die "Can't open directory: $!\n";
    while (my $f = readdir(D)) {
	if ($f =~ /^combined-[0-9]{6}.txt$/) {
	    $f =~ s/combined-//;
	    $f =~ s/.txt$//;
	    push(@cruns, $f);
	    # -- check for last combined/analyzed run that does NOT have NOANALYSIS
	    $bla = `/bin/grep 'NOANALYSIS' problems-combined-$f.txt`;
	    if ($bla =~ "NOANALYSIS") {
	    } else {
		if ($f > $oldRun) {
		    $oldRun = $f;
		}
	    }
	}
    }
    closedir(D);
    @cruns = sort numerically @cruns;

    my @nruns = ();
    foreach $r (@runs) {
	if (!grep(/$r/, @cruns)) {
	    # -- check that they have output from the batch job before adding them
	    if (-e "$BASE/run-$r/tmp-pcl-$r-0000/pcl-$r-0000.sge.log") {
		push(@nruns, $r);
	    }
	}
    }
    @nruns = sort numerically @nruns;
    foreach $r (@nruns) {
	print "new run to harvest:  $r\n";
    }

    # -- harvesting: combine, analysis, grep for non-OK, diff to previous run
    foreach $r (@nruns) {
	print "test/pclDiag -r $r\n";
	if (!$opt_d) {
	    system("test/pclDiag -r $r");
	}

	print "test/pclDiag -f combined-$r.txt\n";
	if (!$opt_d) {
	    if (-e "ana-combined-$r.txt") {unlink("ana-combined-$r.txt");}
	    system("test/pclDiag -f combined-$r.txt > ana-combined-$r.txt");
	}

	print "grep -v OK combined-$r.txt\n";
	if (!$opt_d) {
	    if (-e "problems-combined-$r.txt") {unlink("problems-combined-$r.txt");}
	    system("/bin/grep -v OK ana-combined-$r.txt > problems-combined-$r.txt");
	}

	if ($oldRun > 0) {
	    $bla = `/bin/grep 'NOANALYSIS' problems-combined-$r.txt`;
	    chop($bla);
	    print "============>$bla<==\n";
	    if ($bla =~ "NOANALYSIS") {
		# do not compare, do NOT increase $oldRun!
		next;
	    } else {
		print "diff problems-combined-$oldRun.txt problems-combined-$r.txt\n";
		if (!$opt_d) {
		    if (-e "diff-problems-$oldRun-$r.txt") {unlink("diff-problems-$oldRun-$r.txt");}
		    system("/usr/bin/diff problems-combined-$oldRun.txt problems-combined-$r.txt > diff-problems-$oldRun-$r.txt");
		}
	    }
	}
	$oldRun = $r;
    }

    exit(0);
}


# -- loop over all runs provided
my $runA, $runB, $runS;
my $runDir;
my @files;
foreach $run (@ARGV) {
    @files = ();
    $runA = substr($run, 0, 3);
    $runB = substr($run, 3, 3);
    $runS = $runA . "/" . $runB;
    $runDir = "run-$run";
    unless (-e $runDir) {
	mkdir($runDir);
    }
    if ($opt_r) {
	print "run on local files\n";
	@files = &runLinesLocal($run);
    } elsif (!$opt_r && !$opt_a) {
	@files = &runLines($dasFile, $runS);
	print "replicate files to PSI\n";
	&dataReplica($runDir);
    } elsif ($opt_a) {
	@files = &runLines($dasFile, $runS);
	print "use AAA\n";
    }
    $filename = "$runDir/pcl-$run";
    &mkPyFile(\@files, $filename);
    chdir($runDir);
    system("$submit -t ../../../../../pcl.tar -c ../prodNoComp.csh -m batch -q short.q -r 'PFNS srm://t3se01.psi.ch:8443/srm/managerv2\\?SFN=/pnfs/psi.ch/cms/trivcat%STORAGE1 /store/user/ursl/pixel/pcl/$runDir%SITE T3_CH_PSI' *.py");
    chdir("..");
}
exit(0);



# ----------------------------------------------------------------------
sub runLines() {
    my $lfile = shift(@_);
    my $runpattern = shift(@_);
    open(IN, "$lfile") || die "cannot open $lfile\n";
    my @lines = <IN>;
    close(IN);
    my @lfiles = ();
    foreach $line (@lines) {
	if ($line =~ /$runpattern/) {
	    chop($line);
	    push(@lfiles, $line);
	}
    }
    print "looked for $runpattern, found $#lfiles+1 files\n";
    return @lfiles;
}

# ----------------------------------------------------------------------
sub runLinesLocal() {
    my $run        = shift(@_);
    @sefiles = `srmls $SEPREFIX/store/user/ursl/files/pcl/run-$run`;
    my @lines = grep(/root$/, @sefiles);
    foreach $line (@lines) {
	($bla, $f) = split(/trivcat/, $line, 2);
	chop($f);
	push(@lfiles, $f);
    }
    print "looked for $run, found $#lfiles+1 files\n";
    return @lfiles;
}


# ----------------------------------------------------------------------
sub dataReplica() {
    my $ldir   = shift(@_);

    chdir($ldir);
    open(OUT, ">dr") || die "Cannot open dr for output\n";
    foreach $file (@files) {
	print OUT "$file\n";
    }
    close OUT;

    system("srmmkdir $SEPREFIX/store/user/ursl/files/pcl/$ldir");
    system("data_replica.py --discovery --to-site T3_CH_PSI dr /store/user/ursl/files/pcl/$ldir");
    chdir("..");
}


# ----------------------------------------------------------------------
sub mkPyFile() {
#    my $lfile = shift(@_);
    my ($aref, $lfile) = @_;
    my @array = @$aref;
    my $idx = 0;
    my $njobs = 1;
    if ($opt_n > 0) {
	$njobs = int(($#array+1)/$opt_n);
	my $rest = ($#array+1) % $opt_n;
	if ($rest != 0) {
	    print "njobs = $njobs; rest = $rest\n";
	    $njobs = $njobs + 1;
	}
    } else {
	$opt_n = $#array+1;
    }
    print "njobs = $njobs\n";
    for ($idx = 0; $idx < $njobs; $idx++) {
	$filename = sprintf("%s-%04i.py", $lfile, $idx);
	my $dccounts = $filename;
	($bla, $dccounts) = split(/\//, $dccounts);
	$dccounts =~ s/py$/txt/g;

	$poolsource = "    fileNames = cms.untracked.vstring( *(\n";
	for ($f = $idx*$opt_n; $f < ($idx+1)*$opt_n; $f++) {
	    $poolsource .= "        \"@array[$f]\",\n";
	    if ($f == $#array) {last;}
	}
	$poolsource .= "    ) )";

	open(OUT, ">$filename") || die "cannot open $filename\n";
	print OUT << "EOF";
# ----------------------------------------------------------------------
# -- RECO py template file for running pixel PCL
# ----------------------------------------------------------------------
import os
import FWCore.ParameterSet.Config as cms
process = cms.Process("PCL")


# ----------------------------------------------------------------------
process.load("FWCore.MessageLogger.MessageLogger_cfi")
process.MessageLogger.cerr.threshold = 'INFO'
process.MessageLogger.cerr.FwkReport.reportEvery = 100
process.MessageLogger.categories.append('HLTrigReport')
process.MessageLogger.categories.append('L1GtTrigReport')
process.options = cms.untracked.PSet(
    SkipEvent = cms.untracked.vstring('ProductNotFound'),
    wantSummary = cms.untracked.bool(True)
)

# -- Database configuration
process.load("CondCore.CondDB.CondDB_cfi")

# -- Conditions
process.load("Configuration.StandardSequences.MagneticField_38T_cff")
process.load("Configuration.StandardSequences.GeometryRecoDB_cff")
process.load("RecoVertex.BeamSpotProducer.BeamSpot_cfi")
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_condDBv2_cff")
from Configuration.AlCa.GlobalTag_condDBv2 import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, '80X_dataRun2_Express_v3', '')

# -- number of events
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)

# -- Input files
process.source = cms.Source(
    "PoolSource",
$poolsource
)


process.pcl = cms.EDAnalyzer(
    "PixelPCL",
    verbose            = cms.untracked.int32(0),
    updateMaps         = cms.untracked.bool(False),
    fileName           = cms.untracked.string("$dccounts"),
    pixelClusterLabel  = cms.untracked.InputTag('siPixelClusters::RECO')
)

# -- Path
process.p = cms.Path(
    process.pcl
)

EOF

	close(OUT);
    }
}


# ----------------------------------------------------------------------
sub checkForNewRuns() {
    my $firstRun = 272008;
    # -- read in runs already processed
    open(IN, "$processedRuns") || die "cannot open $processedRuns\n";
    my @runsDone = <IN>;
    close(IN);

    # -- read in all files
    open(IN, "$dasFile") || die "cannot open $dasFile\n";
    my @lines = <IN>;
    close(IN);

    my @runsToDo = ();
    # -- get list of runs
    foreach $line (@lines) {
	$line =~ /([0-9]{3})\/([0-9]{3})\/[0-9]*\/[A-Z,0-9,-]*\.root$/;
	$run = $1.$2;
	if ($run < $firstRun) {next;}
	if (grep(/$run/, @runsDone)) {
	    # print "  already processed\n";
	} else {
	    if (grep(/$run/, @runsToDo)) {
	    } else {
		# print "  adding $run to todo list\n";
		push(@runsToDo, $run);
	    }
	}
    }
    return @runsToDo;
}
